### PR TITLE
can write condition

### PR DESCRIPTION
**Pull request by Wolfer**
can write condition as
# IF:TRUE_COND

show this
# ENDIF:TRUE_COND

### CODE REVIEW

**Comment by tamird** [comment]
Could you rebase this? Sorry for not noticing this PR.

**Comment by Wolfer** [comment]
done

**Comment by tamird** [comment]
Seems that `bundle exec rake` is failing. Could you confirm it passes locally?

**Comment by Wolfer** [comment]
spec task end with
`30 examples, 0 failures`

rubocop task
`9 files inspected, 6 offenses detected `
but above offenses do not apply to my changes

**Comment by tamird** [comment]
Can you `bundle exec update` and try again? Only one offense is coming up in travis, and master is green, so it is probably related to your changes.

**Comment by Wolfer** [comment]
oops, sorry. Fixed. 1 offense already

**Comment by tamird** [comment]
Ah, last remaining offense is `spec/template_processor_spec.rb:37:1: C: Block has too many lines. [177/169]`, you can fix it by running `bundle exec rubocop --auto-gen-config`.

**Comment by Wolfer** [comment]
done

**Comment by tamird** [comment]
Thanks!

**Pull request merged**
